const os = require('os');
const path = require('path');
const fs = require('fs');

const projectRoot = __dirname;
const platform = os.platform();
const pkg = 'tonyfettes/ds4';

const metalSources = [
  ['DS4_METAL_FLASH_ATTN_SOURCE', 'metal/flash_attn.metal'],
  ['DS4_METAL_DENSE_SOURCE', 'metal/dense.metal'],
  ['DS4_METAL_MOE_SOURCE', 'metal/moe.metal'],
  ['DS4_METAL_DSV4_HC_SOURCE', 'metal/dsv4_hc.metal'],
  ['DS4_METAL_UNARY_SOURCE', 'metal/unary.metal'],
  ['DS4_METAL_DSV4_KV_SOURCE', 'metal/dsv4_kv.metal'],
  ['DS4_METAL_DSV4_ROPE_SOURCE', 'metal/dsv4_rope.metal'],
  ['DS4_METAL_DSV4_MISC_SOURCE', 'metal/dsv4_misc.metal'],
  ['DS4_METAL_ARGSORT_SOURCE', 'metal/argsort.metal'],
  ['DS4_METAL_CPY_SOURCE', 'metal/cpy.metal'],
  ['DS4_METAL_CONCAT_SOURCE', 'metal/concat.metal'],
  ['DS4_METAL_GET_ROWS_SOURCE', 'metal/get_rows.metal'],
  ['DS4_METAL_SUM_ROWS_SOURCE', 'metal/sum_rows.metal'],
  ['DS4_METAL_SOFTMAX_SOURCE', 'metal/softmax.metal'],
  ['DS4_METAL_REPEAT_SOURCE', 'metal/repeat.metal'],
  ['DS4_METAL_GLU_SOURCE', 'metal/glu.metal'],
  ['DS4_METAL_NORM_SOURCE', 'metal/norm.metal'],
  ['DS4_METAL_BIN_SOURCE', 'metal/bin.metal'],
  ['DS4_METAL_SET_ROWS_SOURCE', 'metal/set_rows.metal'],
];

function cStringLiteralChunk(chunk) {
  return chunk
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n"\n"');
}

function cStringLiteral(text) {
  const chunks = [];
  for (let i = 0; i < text.length; i += 12000) {
    chunks.push(`"${cStringLiteralChunk(text.slice(i, i + 12000))}"`);
  }
  return chunks.join('\n');
}

function writeEmbeddedMetalSources() {
  const lines = [
    '/* Generated by build.js. Do not edit. */',
  ];
  for (const [env, relPath] of metalSources) {
    const sourcePath = path.join(projectRoot, relPath);
    const source = fs.readFileSync(sourcePath, 'utf8');
    lines.push(`{ "${env}", "${relPath}",`);
    lines.push(cStringLiteral(source));
    lines.push('},');
  }
  lines.push('');
  fs.writeFileSync(path.join(projectRoot, 'ds4_metal_sources.generated.inc'), lines.join('\n'));
}

writeEmbeddedMetalSources();

let stubFlags = `-I${projectRoot}`;
let linkFlags;
let linkConfig = { package: pkg };
if (platform === 'darwin') {
  stubFlags += ' -ObjC -fobjc-arc';
  linkFlags = '-framework Foundation -framework Metal -pthread';
  linkConfig.link_flags = '-framework Foundation -framework Metal -pthread';
} else if (platform === 'linux') {
  stubFlags += ' -DDS4_NO_GPU -D_GNU_SOURCE -fno-finite-math-only';
  linkFlags = '-lm -pthread';
  linkConfig.link_flags = '-lm -pthread';
} else {
  throw new Error(`Unsupported platform for ds4 native binding: ${platform}`);
}

const output = {
  vars: {
    DS4_STUB_CC_FLAGS: stubFlags,
    DS4_CC_LINK_FLAGS: linkFlags,
  },
  link_configs: [linkConfig],
};

console.log(JSON.stringify(output));
